# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'photoOrg_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1183, 980)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 89, 89))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 166, 166))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 84, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 116, 116))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 89, 89))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 166, 166))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 84, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 116, 116))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 84, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 89, 89))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 166, 166))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 84, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 116, 116))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 84, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 84, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lstPhotos = QtWidgets.QListWidget(self.centralwidget)
        self.lstPhotos.setGeometry(QtCore.QRect(20, 70, 611, 871))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lstPhotos.setFont(font)
        self.lstPhotos.setObjectName("lstPhotos")
        self.lblPath = QtWidgets.QLabel(self.centralwidget)
        self.lblPath.setGeometry(QtCore.QRect(420, 10, 731, 23))
        self.lblPath.setObjectName("lblPath")
        self.lblCurrDir = QtWidgets.QLabel(self.centralwidget)
        self.lblCurrDir.setGeometry(QtCore.QRect(210, 10, 191, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.lblCurrDir.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCurrDir.setFont(font)
        self.lblCurrDir.setObjectName("lblCurrDir")
        self.lblNewName = QtWidgets.QLabel(self.centralwidget)
        self.lblNewName.setGeometry(QtCore.QRect(210, 40, 191, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.lblNewName.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblNewName.setFont(font)
        self.lblNewName.setObjectName("lblNewName")
        self.lblSampleNewFilename = QtWidgets.QLabel(self.centralwidget)
        self.lblSampleNewFilename.setGeometry(QtCore.QRect(420, 40, 731, 23))
        self.lblSampleNewFilename.setObjectName("lblSampleNewFilename")
        self.btnOpen = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpen.setGeometry(QtCore.QRect(20, 15, 150, 47))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(130, 130, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(130, 130, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 84, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(130, 130, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnOpen.setPalette(palette)
        self.btnOpen.setObjectName("btnOpen")
        self.tabOptions = QtWidgets.QTabWidget(self.centralwidget)
        self.tabOptions.setGeometry(QtCore.QRect(690, 385, 440, 561))
        self.tabOptions.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabOptions.setUsesScrollButtons(True)
        self.tabOptions.setObjectName("tabOptions")
        self.tabRename = QtWidgets.QWidget()
        self.tabRename.setObjectName("tabRename")
        self.btnRename = QtWidgets.QPushButton(self.tabRename)
        self.btnRename.setGeometry(QtCore.QRect(200, 470, 180, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(130, 130, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(130, 130, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 84, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(130, 130, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnRename.setPalette(palette)
        self.btnRename.setObjectName("btnRename")
        self.chkSidecars = QtWidgets.QCheckBox(self.tabRename)
        self.chkSidecars.setGeometry(QtCore.QRect(20, 420, 361, 28))
        self.chkSidecars.setChecked(True)
        self.chkSidecars.setObjectName("chkSidecars")
        self.cboRenameFiles = QtWidgets.QComboBox(self.tabRename)
        self.cboRenameFiles.setGeometry(QtCore.QRect(150, 20, 270, 33))
        self.cboRenameFiles.setObjectName("cboRenameFiles")
        self.lblFiles = QtWidgets.QLabel(self.tabRename)
        self.lblFiles.setGeometry(QtCore.QRect(20, 25, 120, 23))
        self.lblFiles.setObjectName("lblFiles")
        self.cboNumbers = QtWidgets.QComboBox(self.tabRename)
        self.cboNumbers.setGeometry(QtCore.QRect(150, 100, 270, 33))
        self.cboNumbers.setObjectName("cboNumbers")
        self.lblNumbers = QtWidgets.QLabel(self.tabRename)
        self.lblNumbers.setGeometry(QtCore.QRect(20, 105, 120, 23))
        self.lblNumbers.setObjectName("lblNumbers")
        self.txtStartNumber = QtWidgets.QLineEdit(self.tabRename)
        self.txtStartNumber.setGeometry(QtCore.QRect(240, 140, 180, 33))
        self.txtStartNumber.setInputMask("")
        self.txtStartNumber.setText("")
        self.txtStartNumber.setObjectName("txtStartNumber")
        self.lblStartValue = QtWidgets.QLabel(self.tabRename)
        self.lblStartValue.setGeometry(QtCore.QRect(150, 145, 90, 23))
        self.lblStartValue.setObjectName("lblStartValue")
        self.label = QtWidgets.QLabel(self.tabRename)
        self.label.setGeometry(QtCore.QRect(20, 185, 120, 23))
        self.label.setObjectName("label")
        self.cboFilenameBase = QtWidgets.QComboBox(self.tabRename)
        self.cboFilenameBase.setGeometry(QtCore.QRect(150, 180, 270, 33))
        self.cboFilenameBase.setObjectName("cboFilenameBase")
        self.txtFilename = QtWidgets.QLineEdit(self.tabRename)
        self.txtFilename.setGeometry(QtCore.QRect(240, 220, 180, 33))
        self.txtFilename.setObjectName("txtFilename")
        self.lblFilename = QtWidgets.QLabel(self.tabRename)
        self.lblFilename.setGeometry(QtCore.QRect(150, 225, 71, 23))
        self.lblFilename.setObjectName("lblFilename")
        self.cboDateOptions = QtWidgets.QComboBox(self.tabRename)
        self.cboDateOptions.setGeometry(QtCore.QRect(150, 260, 270, 33))
        self.cboDateOptions.setObjectName("cboDateOptions")
        self.label_4 = QtWidgets.QLabel(self.tabRename)
        self.label_4.setGeometry(QtCore.QRect(20, 265, 120, 23))
        self.label_4.setObjectName("label_4")
        self.txtDatePattern = QtWidgets.QLineEdit(self.tabRename)
        self.txtDatePattern.setGeometry(QtCore.QRect(240, 300, 180, 33))
        self.txtDatePattern.setObjectName("txtDatePattern")
        self.lblDatePattern = QtWidgets.QLabel(self.tabRename)
        self.lblDatePattern.setGeometry(QtCore.QRect(150, 305, 81, 23))
        self.lblDatePattern.setObjectName("lblDatePattern")
        self.cboSuffix = QtWidgets.QComboBox(self.tabRename)
        self.cboSuffix.setGeometry(QtCore.QRect(150, 340, 270, 33))
        self.cboSuffix.setObjectName("cboSuffix")
        self.lblSuffix = QtWidgets.QLabel(self.tabRename)
        self.lblSuffix.setGeometry(QtCore.QRect(20, 345, 120, 23))
        self.lblSuffix.setObjectName("lblSuffix")
        self.txtSuffix = QtWidgets.QLineEdit(self.tabRename)
        self.txtSuffix.setGeometry(QtCore.QRect(240, 380, 180, 33))
        self.txtSuffix.setObjectName("txtSuffix")
        self.lblCustomSuffix = QtWidgets.QLabel(self.tabRename)
        self.lblCustomSuffix.setGeometry(QtCore.QRect(150, 385, 81, 23))
        self.lblCustomSuffix.setObjectName("lblCustomSuffix")
        self.cboNumberPosition = QtWidgets.QComboBox(self.tabRename)
        self.cboNumberPosition.setGeometry(QtCore.QRect(150, 60, 270, 33))
        self.cboNumberPosition.setObjectName("cboNumberPosition")
        self.label_3 = QtWidgets.QLabel(self.tabRename)
        self.label_3.setGeometry(QtCore.QRect(20, 65, 120, 23))
        self.label_3.setObjectName("label_3")
        self.tabOptions.addTab(self.tabRename, "")
        self.tabExifData = QtWidgets.QWidget()
        self.tabExifData.setObjectName("tabExifData")
        self.txtCameraMake = QtWidgets.QLineEdit(self.tabExifData)
        self.txtCameraMake.setGeometry(QtCore.QRect(200, 60, 220, 33))
        self.txtCameraMake.setObjectName("txtCameraMake")
        self.chkCameraMake = QtWidgets.QCheckBox(self.tabExifData)
        self.chkCameraMake.setGeometry(QtCore.QRect(20, 65, 175, 28))
        self.chkCameraMake.setObjectName("chkCameraMake")
        self.chkCameraModel = QtWidgets.QCheckBox(self.tabExifData)
        self.chkCameraModel.setGeometry(QtCore.QRect(20, 105, 175, 28))
        self.chkCameraModel.setObjectName("chkCameraModel")
        self.txtCameraModel = QtWidgets.QLineEdit(self.tabExifData)
        self.txtCameraModel.setGeometry(QtCore.QRect(200, 100, 220, 33))
        self.txtCameraModel.setObjectName("txtCameraModel")
        self.chkImageDescription = QtWidgets.QCheckBox(self.tabExifData)
        self.chkImageDescription.setGeometry(QtCore.QRect(20, 145, 175, 28))
        self.chkImageDescription.setObjectName("chkImageDescription")
        self.txtImageDescription = QtWidgets.QLineEdit(self.tabExifData)
        self.txtImageDescription.setGeometry(QtCore.QRect(200, 140, 220, 33))
        self.txtImageDescription.setObjectName("txtImageDescription")
        self.btnChangeExif = QtWidgets.QPushButton(self.tabExifData)
        self.btnChangeExif.setGeometry(QtCore.QRect(200, 470, 180, 40))
        self.btnChangeExif.setObjectName("btnChangeExif")
        self.chkEmbedThumbnail = QtWidgets.QCheckBox(self.tabExifData)
        self.chkEmbedThumbnail.setGeometry(QtCore.QRect(20, 385, 175, 28))
        self.chkEmbedThumbnail.setObjectName("chkEmbedThumbnail")
        self.cboExifFiles = QtWidgets.QComboBox(self.tabExifData)
        self.cboExifFiles.setGeometry(QtCore.QRect(200, 20, 220, 33))
        self.cboExifFiles.setObjectName("cboExifFiles")
        self.lblExifFiles = QtWidgets.QLabel(self.tabExifData)
        self.lblExifFiles.setGeometry(QtCore.QRect(20, 25, 161, 23))
        self.lblExifFiles.setObjectName("lblExifFiles")
        self.cboThumbnail = QtWidgets.QComboBox(self.tabExifData)
        self.cboThumbnail.setGeometry(QtCore.QRect(200, 380, 220, 33))
        self.cboThumbnail.setObjectName("cboThumbnail")
        self.chkArtist = QtWidgets.QCheckBox(self.tabExifData)
        self.chkArtist.setGeometry(QtCore.QRect(20, 305, 175, 28))
        self.chkArtist.setObjectName("chkArtist")
        self.chkCopyright = QtWidgets.QCheckBox(self.tabExifData)
        self.chkCopyright.setGeometry(QtCore.QRect(20, 345, 175, 28))
        self.chkCopyright.setObjectName("chkCopyright")
        self.txtArtist = QtWidgets.QLineEdit(self.tabExifData)
        self.txtArtist.setGeometry(QtCore.QRect(200, 300, 220, 33))
        self.txtArtist.setObjectName("txtArtist")
        self.txtCopyright = QtWidgets.QLineEdit(self.tabExifData)
        self.txtCopyright.setGeometry(QtCore.QRect(200, 340, 220, 33))
        self.txtCopyright.setObjectName("txtCopyright")
        self.txtUserComment = QtWidgets.QLineEdit(self.tabExifData)
        self.txtUserComment.setGeometry(QtCore.QRect(200, 180, 220, 33))
        self.txtUserComment.setObjectName("txtUserComment")
        self.chkUserComment = QtWidgets.QCheckBox(self.tabExifData)
        self.chkUserComment.setGeometry(QtCore.QRect(20, 185, 175, 28))
        self.chkUserComment.setObjectName("chkUserComment")
        self.txtLensMake = QtWidgets.QLineEdit(self.tabExifData)
        self.txtLensMake.setGeometry(QtCore.QRect(200, 220, 220, 33))
        self.txtLensMake.setObjectName("txtLensMake")
        self.chkLensMake = QtWidgets.QCheckBox(self.tabExifData)
        self.chkLensMake.setGeometry(QtCore.QRect(20, 225, 175, 28))
        self.chkLensMake.setObjectName("chkLensMake")
        self.txtLensModel = QtWidgets.QLineEdit(self.tabExifData)
        self.txtLensModel.setGeometry(QtCore.QRect(200, 260, 220, 33))
        self.txtLensModel.setObjectName("txtLensModel")
        self.chkLensModel = QtWidgets.QCheckBox(self.tabExifData)
        self.chkLensModel.setGeometry(QtCore.QRect(20, 265, 175, 28))
        self.chkLensModel.setObjectName("chkLensModel")
        self.tabOptions.addTab(self.tabExifData, "")
        self.tabDate = QtWidgets.QWidget()
        self.tabDate.setObjectName("tabDate")
        self.txtDay = QtWidgets.QLineEdit(self.tabDate)
        self.txtDay.setGeometry(QtCore.QRect(330, 130, 40, 33))
        self.txtDay.setObjectName("txtDay")
        self.cboDateEdit = QtWidgets.QComboBox(self.tabDate)
        self.cboDateEdit.setGeometry(QtCore.QRect(200, 70, 220, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboDateEdit.sizePolicy().hasHeightForWidth())
        self.cboDateEdit.setSizePolicy(sizePolicy)
        self.cboDateEdit.setObjectName("cboDateEdit")
        self.txtSecond = QtWidgets.QLineEdit(self.tabDate)
        self.txtSecond.setGeometry(QtCore.QRect(330, 240, 40, 33))
        self.txtSecond.setObjectName("txtSecond")
        self.lblYear = QtWidgets.QLabel(self.tabDate)
        self.lblYear.setGeometry(QtCore.QRect(200, 105, 71, 23))
        self.lblYear.setObjectName("lblYear")
        self.lblHour = QtWidgets.QLabel(self.tabDate)
        self.lblHour.setGeometry(QtCore.QRect(200, 215, 61, 23))
        self.lblHour.setObjectName("lblHour")
        self.txtMinute = QtWidgets.QLineEdit(self.tabDate)
        self.txtMinute.setGeometry(QtCore.QRect(280, 240, 40, 33))
        self.txtMinute.setObjectName("txtMinute")
        self.cboTimeEdit = QtWidgets.QComboBox(self.tabDate)
        self.cboTimeEdit.setGeometry(QtCore.QRect(200, 180, 220, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboTimeEdit.sizePolicy().hasHeightForWidth())
        self.cboTimeEdit.setSizePolicy(sizePolicy)
        self.cboTimeEdit.setObjectName("cboTimeEdit")
        self.chkOriginalDate = QtWidgets.QCheckBox(self.tabDate)
        self.chkOriginalDate.setGeometry(QtCore.QRect(20, 70, 171, 28))
        self.chkOriginalDate.setObjectName("chkOriginalDate")
        self.lblDay = QtWidgets.QLabel(self.tabDate)
        self.lblDay.setGeometry(QtCore.QRect(330, 105, 41, 23))
        self.lblDay.setObjectName("lblDay")
        self.lblMonth = QtWidgets.QLabel(self.tabDate)
        self.lblMonth.setGeometry(QtCore.QRect(280, 105, 41, 23))
        self.lblMonth.setObjectName("lblMonth")
        self.lblMinute = QtWidgets.QLabel(self.tabDate)
        self.lblMinute.setGeometry(QtCore.QRect(280, 215, 41, 23))
        self.lblMinute.setObjectName("lblMinute")
        self.lblSeconds = QtWidgets.QLabel(self.tabDate)
        self.lblSeconds.setGeometry(QtCore.QRect(330, 215, 41, 23))
        self.lblSeconds.setObjectName("lblSeconds")
        self.cboTimeShift = QtWidgets.QComboBox(self.tabDate)
        self.cboTimeShift.setGeometry(QtCore.QRect(200, 290, 220, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboTimeShift.sizePolicy().hasHeightForWidth())
        self.cboTimeShift.setSizePolicy(sizePolicy)
        self.cboTimeShift.setObjectName("cboTimeShift")
        self.chkShiftDate = QtWidgets.QCheckBox(self.tabDate)
        self.chkShiftDate.setGeometry(QtCore.QRect(20, 290, 181, 28))
        self.chkShiftDate.setObjectName("chkShiftDate")
        self.txtMonth = QtWidgets.QLineEdit(self.tabDate)
        self.txtMonth.setGeometry(QtCore.QRect(280, 130, 40, 33))
        self.txtMonth.setObjectName("txtMonth")
        self.txtYear = QtWidgets.QLineEdit(self.tabDate)
        self.txtYear.setGeometry(QtCore.QRect(200, 130, 70, 33))
        self.txtYear.setObjectName("txtYear")
        self.txtHour = QtWidgets.QLineEdit(self.tabDate)
        self.txtHour.setGeometry(QtCore.QRect(200, 240, 70, 33))
        self.txtHour.setObjectName("txtHour")
        self.txtShiftHour = QtWidgets.QLineEdit(self.tabDate)
        self.txtShiftHour.setGeometry(QtCore.QRect(200, 410, 70, 33))
        self.txtShiftHour.setObjectName("txtShiftHour")
        self.lblDay_2 = QtWidgets.QLabel(self.tabDate)
        self.lblDay_2.setGeometry(QtCore.QRect(330, 385, 41, 23))
        self.lblDay_2.setObjectName("lblDay_2")
        self.lblMonth_2 = QtWidgets.QLabel(self.tabDate)
        self.lblMonth_2.setGeometry(QtCore.QRect(280, 385, 41, 23))
        self.lblMonth_2.setObjectName("lblMonth_2")
        self.txtShiftMinute = QtWidgets.QLineEdit(self.tabDate)
        self.txtShiftMinute.setGeometry(QtCore.QRect(280, 410, 40, 33))
        self.txtShiftMinute.setObjectName("txtShiftMinute")
        self.lblYear_2 = QtWidgets.QLabel(self.tabDate)
        self.lblYear_2.setGeometry(QtCore.QRect(200, 385, 71, 23))
        self.lblYear_2.setObjectName("lblYear_2")
        self.txtShiftSecond = QtWidgets.QLineEdit(self.tabDate)
        self.txtShiftSecond.setGeometry(QtCore.QRect(330, 410, 40, 33))
        self.txtShiftSecond.setObjectName("txtShiftSecond")
        self.txtShiftYear = QtWidgets.QLineEdit(self.tabDate)
        self.txtShiftYear.setGeometry(QtCore.QRect(200, 345, 70, 33))
        self.txtShiftYear.setObjectName("txtShiftYear")
        self.lblDay_3 = QtWidgets.QLabel(self.tabDate)
        self.lblDay_3.setGeometry(QtCore.QRect(330, 320, 41, 23))
        self.lblDay_3.setObjectName("lblDay_3")
        self.lblMonth_3 = QtWidgets.QLabel(self.tabDate)
        self.lblMonth_3.setGeometry(QtCore.QRect(280, 320, 41, 23))
        self.lblMonth_3.setObjectName("lblMonth_3")
        self.txtShiftMonth = QtWidgets.QLineEdit(self.tabDate)
        self.txtShiftMonth.setGeometry(QtCore.QRect(280, 345, 40, 33))
        self.txtShiftMonth.setObjectName("txtShiftMonth")
        self.lblYear_3 = QtWidgets.QLabel(self.tabDate)
        self.lblYear_3.setGeometry(QtCore.QRect(200, 320, 71, 23))
        self.lblYear_3.setObjectName("lblYear_3")
        self.txtShiftDay = QtWidgets.QLineEdit(self.tabDate)
        self.txtShiftDay.setGeometry(QtCore.QRect(330, 345, 40, 33))
        self.txtShiftDay.setObjectName("txtShiftDay")
        self.btnChangeDate = QtWidgets.QPushButton(self.tabDate)
        self.btnChangeDate.setGeometry(QtCore.QRect(200, 470, 180, 40))
        self.btnChangeDate.setObjectName("btnChangeDate")
        self.lblDates = QtWidgets.QLabel(self.tabDate)
        self.lblDates.setGeometry(QtCore.QRect(20, 25, 161, 23))
        self.lblDates.setObjectName("lblDates")
        self.cboDateFiles = QtWidgets.QComboBox(self.tabDate)
        self.cboDateFiles.setGeometry(QtCore.QRect(200, 20, 220, 33))
        self.cboDateFiles.setObjectName("cboDateFiles")
        self.timeOriginalDate = QtWidgets.QDateTimeEdit(self.tabDate)
        self.timeOriginalDate.setGeometry(QtCore.QRect(400, 130, 20, 33))
        self.timeOriginalDate.setCalendarPopup(True)
        self.timeOriginalDate.setObjectName("timeOriginalDate")
        self.chkOriginalTime = QtWidgets.QCheckBox(self.tabDate)
        self.chkOriginalTime.setGeometry(QtCore.QRect(20, 180, 171, 28))
        self.chkOriginalTime.setObjectName("chkOriginalTime")
        self.tabOptions.addTab(self.tabDate, "")
        self.tabRotate = QtWidgets.QWidget()
        self.tabRotate.setObjectName("tabRotate")
        self.cboRotate = QtWidgets.QComboBox(self.tabRotate)
        self.cboRotate.setGeometry(QtCore.QRect(200, 60, 220, 33))
        self.cboRotate.setObjectName("cboRotate")
        self.label_2 = QtWidgets.QLabel(self.tabRotate)
        self.label_2.setGeometry(QtCore.QRect(20, 65, 161, 23))
        self.label_2.setObjectName("label_2")
        self.btnRotate = QtWidgets.QPushButton(self.tabRotate)
        self.btnRotate.setGeometry(QtCore.QRect(200, 470, 180, 40))
        self.btnRotate.setObjectName("btnRotate")
        self.lblDates_2 = QtWidgets.QLabel(self.tabRotate)
        self.lblDates_2.setGeometry(QtCore.QRect(20, 25, 161, 23))
        self.lblDates_2.setObjectName("lblDates_2")
        self.cboRotateFiles = QtWidgets.QComboBox(self.tabRotate)
        self.cboRotateFiles.setGeometry(QtCore.QRect(200, 20, 220, 33))
        self.cboRotateFiles.setObjectName("cboRotateFiles")
        self.label_5 = QtWidgets.QLabel(self.tabRotate)
        self.label_5.setGeometry(QtCore.QRect(20, 105, 161, 23))
        self.label_5.setObjectName("label_5")
        self.cboMirror = QtWidgets.QComboBox(self.tabRotate)
        self.cboMirror.setGeometry(QtCore.QRect(200, 100, 220, 33))
        self.cboMirror.setObjectName("cboMirror")
        self.tabOptions.addTab(self.tabRotate, "")
        self.tabDelete = QtWidgets.QWidget()
        self.tabDelete.setObjectName("tabDelete")
        self.btnDelete = QtWidgets.QPushButton(self.tabDelete)
        self.btnDelete.setGeometry(QtCore.QRect(200, 470, 180, 40))
        self.btnDelete.setObjectName("btnDelete")
        self.label_6 = QtWidgets.QLabel(self.tabDelete)
        self.label_6.setGeometry(QtCore.QRect(30, 40, 371, 151))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.chkDelete = QtWidgets.QCheckBox(self.tabDelete)
        self.chkDelete.setGeometry(QtCore.QRect(30, 240, 381, 28))
        self.chkDelete.setObjectName("chkDelete")
        self.chkDeleteXMP = QtWidgets.QCheckBox(self.tabDelete)
        self.chkDeleteXMP.setGeometry(QtCore.QRect(30, 280, 381, 28))
        self.chkDeleteXMP.setObjectName("chkDeleteXMP")
        self.tabOptions.addTab(self.tabDelete, "")
        self.lblBigPhoto = QtWidgets.QLabel(self.centralwidget)
        self.lblBigPhoto.setGeometry(QtCore.QRect(660, 70, 500, 281))
        self.lblBigPhoto.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblBigPhoto.setText("")
        self.lblBigPhoto.setScaledContents(False)
        self.lblBigPhoto.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBigPhoto.setObjectName("lblBigPhoto")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(690, 185, 440, 51))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lblProgressBar = QtWidgets.QLabel(self.centralwidget)
        self.lblProgressBar.setGeometry(QtCore.QRect(690, 250, 441, 23))
        self.lblProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.lblProgressBar.setObjectName("lblProgressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1183, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSort = QtWidgets.QMenu(self.menubar)
        self.menuSort.setObjectName("menuSort")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_Files = QtWidgets.QAction(MainWindow)
        self.actionOpen_Files.setObjectName("actionOpen_Files")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionDelete_temporary_thumbnail_files = QtWidgets.QAction(MainWindow)
        self.actionDelete_temporary_thumbnail_files.setObjectName("actionDelete_temporary_thumbnail_files")
        self.actionSortPhotoListByOriginalDate = QtWidgets.QAction(MainWindow)
        self.actionSortPhotoListByOriginalDate.setObjectName("actionSortPhotoListByOriginalDate")
        self.actionSortPhotoListAlphabetically = QtWidgets.QAction(MainWindow)
        self.actionSortPhotoListAlphabetically.setObjectName("actionSortPhotoListAlphabetically")
        self.menuFile.addAction(self.actionOpen_Files)
        self.menuFile.addAction(self.actionExit)
        self.menuSort.addAction(self.actionSortPhotoListAlphabetically)
        self.menuSort.addAction(self.actionSortPhotoListByOriginalDate)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSort.menuAction())

        self.retranslateUi(MainWindow)
        self.tabOptions.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btnOpen, self.cboRenameFiles)
        MainWindow.setTabOrder(self.cboRenameFiles, self.cboNumberPosition)
        MainWindow.setTabOrder(self.cboNumberPosition, self.cboNumbers)
        MainWindow.setTabOrder(self.cboNumbers, self.txtStartNumber)
        MainWindow.setTabOrder(self.txtStartNumber, self.cboFilenameBase)
        MainWindow.setTabOrder(self.cboFilenameBase, self.txtFilename)
        MainWindow.setTabOrder(self.txtFilename, self.cboDateOptions)
        MainWindow.setTabOrder(self.cboDateOptions, self.txtDatePattern)
        MainWindow.setTabOrder(self.txtDatePattern, self.cboSuffix)
        MainWindow.setTabOrder(self.cboSuffix, self.txtSuffix)
        MainWindow.setTabOrder(self.txtSuffix, self.chkSidecars)
        MainWindow.setTabOrder(self.chkSidecars, self.btnRename)
        MainWindow.setTabOrder(self.btnRename, self.cboExifFiles)
        MainWindow.setTabOrder(self.cboExifFiles, self.chkCameraMake)
        MainWindow.setTabOrder(self.chkCameraMake, self.txtCameraMake)
        MainWindow.setTabOrder(self.txtCameraMake, self.chkCameraModel)
        MainWindow.setTabOrder(self.chkCameraModel, self.txtCameraModel)
        MainWindow.setTabOrder(self.txtCameraModel, self.chkImageDescription)
        MainWindow.setTabOrder(self.chkImageDescription, self.txtImageDescription)
        MainWindow.setTabOrder(self.txtImageDescription, self.chkUserComment)
        MainWindow.setTabOrder(self.chkUserComment, self.txtUserComment)
        MainWindow.setTabOrder(self.txtUserComment, self.chkLensMake)
        MainWindow.setTabOrder(self.chkLensMake, self.txtLensMake)
        MainWindow.setTabOrder(self.txtLensMake, self.chkLensModel)
        MainWindow.setTabOrder(self.chkLensModel, self.txtLensModel)
        MainWindow.setTabOrder(self.txtLensModel, self.chkArtist)
        MainWindow.setTabOrder(self.chkArtist, self.txtArtist)
        MainWindow.setTabOrder(self.txtArtist, self.chkCopyright)
        MainWindow.setTabOrder(self.chkCopyright, self.txtCopyright)
        MainWindow.setTabOrder(self.txtCopyright, self.chkEmbedThumbnail)
        MainWindow.setTabOrder(self.chkEmbedThumbnail, self.cboThumbnail)
        MainWindow.setTabOrder(self.cboThumbnail, self.btnChangeExif)
        MainWindow.setTabOrder(self.btnChangeExif, self.cboDateFiles)
        MainWindow.setTabOrder(self.cboDateFiles, self.chkOriginalDate)
        MainWindow.setTabOrder(self.chkOriginalDate, self.cboDateEdit)
        MainWindow.setTabOrder(self.cboDateEdit, self.txtYear)
        MainWindow.setTabOrder(self.txtYear, self.txtMonth)
        MainWindow.setTabOrder(self.txtMonth, self.txtDay)
        MainWindow.setTabOrder(self.txtDay, self.timeOriginalDate)
        MainWindow.setTabOrder(self.timeOriginalDate, self.chkOriginalTime)
        MainWindow.setTabOrder(self.chkOriginalTime, self.cboTimeEdit)
        MainWindow.setTabOrder(self.cboTimeEdit, self.txtHour)
        MainWindow.setTabOrder(self.txtHour, self.txtMinute)
        MainWindow.setTabOrder(self.txtMinute, self.txtSecond)
        MainWindow.setTabOrder(self.txtSecond, self.chkShiftDate)
        MainWindow.setTabOrder(self.chkShiftDate, self.cboTimeShift)
        MainWindow.setTabOrder(self.cboTimeShift, self.txtShiftYear)
        MainWindow.setTabOrder(self.txtShiftYear, self.txtShiftMonth)
        MainWindow.setTabOrder(self.txtShiftMonth, self.txtShiftDay)
        MainWindow.setTabOrder(self.txtShiftDay, self.txtShiftHour)
        MainWindow.setTabOrder(self.txtShiftHour, self.txtShiftMinute)
        MainWindow.setTabOrder(self.txtShiftMinute, self.txtShiftSecond)
        MainWindow.setTabOrder(self.txtShiftSecond, self.btnChangeDate)
        MainWindow.setTabOrder(self.btnChangeDate, self.cboRotate)
        MainWindow.setTabOrder(self.cboRotate, self.btnRotate)
        MainWindow.setTabOrder(self.btnRotate, self.tabOptions)
        MainWindow.setTabOrder(self.tabOptions, self.lstPhotos)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tripod"))
        self.lblPath.setText(_translate("MainWindow", "No files selected"))
        self.lblCurrDir.setText(_translate("MainWindow", "Current Directory:"))
        self.lblNewName.setText(_translate("MainWindow", "New Filename:"))
        self.lblSampleNewFilename.setText(_translate("MainWindow", "No files selected"))
        self.btnOpen.setText(_translate("MainWindow", "Choose Files"))
        self.btnRename.setText(_translate("MainWindow", "Rename Files"))
        self.chkSidecars.setText(_translate("MainWindow", "Rename corresponding XMP files"))
        self.lblFiles.setText(_translate("MainWindow", "Files"))
        self.lblNumbers.setText(_translate("MainWindow", "Number"))
        self.lblStartValue.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "Base name"))
        self.lblFilename.setText(_translate("MainWindow", "Base"))
        self.label_4.setText(_translate("MainWindow", "Date Taken"))
        self.txtDatePattern.setToolTip(_translate("MainWindow", "Use YMDhms format"))
        self.lblDatePattern.setText(_translate("MainWindow", "Pattern"))
        self.lblSuffix.setText(_translate("MainWindow", "Suffix"))
        self.lblCustomSuffix.setText(_translate("MainWindow", "Suffix"))
        self.label_3.setText(_translate("MainWindow", "Position"))
        self.tabOptions.setTabText(self.tabOptions.indexOf(self.tabRename), _translate("MainWindow", "Rename"))
        self.chkCameraMake.setText(_translate("MainWindow", "Camera Make"))
        self.chkCameraModel.setText(_translate("MainWindow", "Camera Model"))
        self.chkImageDescription.setText(_translate("MainWindow", "Img Description"))
        self.btnChangeExif.setText(_translate("MainWindow", "Change EXIF Data"))
        self.chkEmbedThumbnail.setText(_translate("MainWindow", "Thumbnail"))
        self.lblExifFiles.setText(_translate("MainWindow", "Files"))
        self.chkArtist.setText(_translate("MainWindow", "Artist"))
        self.chkCopyright.setText(_translate("MainWindow", "Copyright"))
        self.chkUserComment.setText(_translate("MainWindow", "User Comment"))
        self.chkLensMake.setText(_translate("MainWindow", "Lens Make"))
        self.chkLensModel.setText(_translate("MainWindow", "Lens Model"))
        self.tabOptions.setTabText(self.tabOptions.indexOf(self.tabExifData), _translate("MainWindow", "EXIF Data"))
        self.lblYear.setText(_translate("MainWindow", "Year"))
        self.lblHour.setText(_translate("MainWindow", "Hr (24)"))
        self.chkOriginalDate.setText(_translate("MainWindow", "Date Taken"))
        self.lblDay.setText(_translate("MainWindow", "Day"))
        self.lblMonth.setText(_translate("MainWindow", "Mo"))
        self.lblMinute.setText(_translate("MainWindow", "Min"))
        self.lblSeconds.setText(_translate("MainWindow", "Sec"))
        self.chkShiftDate.setText(_translate("MainWindow", "Shift"))
        self.lblDay_2.setText(_translate("MainWindow", "Sec"))
        self.lblMonth_2.setText(_translate("MainWindow", "Min"))
        self.lblYear_2.setText(_translate("MainWindow", "Hr (24)"))
        self.lblDay_3.setText(_translate("MainWindow", "Day"))
        self.lblMonth_3.setText(_translate("MainWindow", "Mo"))
        self.lblYear_3.setText(_translate("MainWindow", "Year"))
        self.btnChangeDate.setText(_translate("MainWindow", "Change Exif Date"))
        self.lblDates.setText(_translate("MainWindow", "Files"))
        self.chkOriginalTime.setText(_translate("MainWindow", "Time Taken"))
        self.tabOptions.setTabText(self.tabOptions.indexOf(self.tabDate), _translate("MainWindow", "Date"))
        self.label_2.setText(_translate("MainWindow", "Rotation"))
        self.btnRotate.setText(_translate("MainWindow", "Rotate Image"))
        self.lblDates_2.setText(_translate("MainWindow", "Files"))
        self.label_5.setText(_translate("MainWindow", "Mirror"))
        self.tabOptions.setTabText(self.tabOptions.indexOf(self.tabRotate), _translate("MainWindow", "Rotate"))
        self.btnDelete.setText(_translate("MainWindow", "Delete Images"))
        self.label_6.setText(_translate("MainWindow", "Delete all SELECTED images. This operation cannot be undone."))
        self.chkDelete.setText(_translate("MainWindow", "Permanently delete selected files"))
        self.chkDeleteXMP.setText(_translate("MainWindow", "Delete corresponding XMP files"))
        self.tabOptions.setTabText(self.tabOptions.indexOf(self.tabDelete), _translate("MainWindow", "Delete"))
        self.lblProgressBar.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSort.setTitle(_translate("MainWindow", "Sort"))
        self.actionOpen_Files.setText(_translate("MainWindow", "Open Files..."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionDelete_temporary_thumbnail_files.setText(_translate("MainWindow", "Delete temporary thumbnail files"))
        self.actionSortPhotoListByOriginalDate.setText(_translate("MainWindow", "Sort by Photo Original Date"))
        self.actionSortPhotoListAlphabetically.setText(_translate("MainWindow", "Sort Alphabetically"))

